x-reinvent-base: &reinvent-base
  image: htvs-pipeline:latest
  working_dir: /workspace
  volumes:
    - .:/workspace
  env_file:
    - host.env
  environment:
    PYTHONUNBUFFERED: "1"
  restart: "no"
  stop_grace_period: 180s
  stop_signal: SIGTERM
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"

services:
  builder:
    build:
      context: .
    image: htvs-pipeline:latest
    entrypoint: ["echo", "Schema builder service"]

  tl:
    <<: *reinvent-base
    container_name: reinvent4-tl
    depends_on:
      - builder
    command: ["/opt/conda/envs/reinvent4/bin/reinvent",
              "-l", "tl.log", "configs/tl_mol2mol.toml"]

  sample:
    <<: *reinvent-base
    container_name: reinvent4-sample
    depends_on:
      - builder
    command: ["/opt/conda/envs/reinvent4/bin/reinvent",
              "-l", "sampling.log", "configs/sample_mol2mol.toml"]

  dock:
    <<: *reinvent-base
    container_name: reinvent4-dock
    depends_on:
      - builder
    command: ["bash", "/workspace/scripts/dock.sh"]

  rl:
    <<: *reinvent-base
    container_name: reinvent4-dock
    depends_on:
      - builder
    command: ["/opt/conda/envs/reinvent4/bin/reinvent",
              "-l", "rl.log", "configs/staged_learning.toml"]

  tensorboard:   
    <<: *reinvent-base
    container_name: reinvent-tb
    depends_on:
      - builder
    working_dir: /workspace
    command: ["/opt/conda/envs/reinvent4/bin/tensorboard",
              "--logdir", "/workspace/tb_TL",
              "--host", "0.0.0.0", "--port", "6006"]
    volumes:
      - ${PWD}:/workspace:ro
    ports:
      - "6006:6006"
    restart: unless-stopped
